### ISSUE TITLE
Basic usage tutorial

### ISSUE THREAD

**Issue by zhmq0124v** [timols/java-gitlab-api#102]
Dear gurus,

I am currently trying to get project list and branches of a project, but my code failed at the beginning. The exception is
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.

Here is my code:
                final String URL = "https://example.com";
		final String token = "myToken";
		api = GitlabAPI.connect(URL, token);
		System.out.println(api.getProjects().size());

Could you please take a look?
A basic tutorial in readme would be better, I tried gitlab python API it works but I prefer to use Java.
Thanks.

**Comment by rockwotj** [comment]
It works for me.
```
GitlabAPI api = GitlabAPI.connect("https://gitlab.com", private_token);
System.out.println(api.getProjects().size());
```
I made sure to grab the token from https://gitlab.com/profile/account or whatever it is for your server. If your token is right try visiting the url in your browser to make sure you get JSON (it sounds like the response is HTML).

Try this url, with the right hostname and token:
https://gitlab.com/api/v3/projects?private_token=<private_token>

**Comment by zhmq0124v** [comment]
Thanks, your url works perfectly.
But when run my Java console application, I still get the following exception:
Exception in thread "main" org.gitlab.api.GitlabAPIException
	at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:361)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:149)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:119)
	at org.gitlab.api.GitlabAPI.getCurrentSession(GitlabAPI.java:1519)
	at git2jira.UpdateIssues.main(UpdateIssues.java:21)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 1875165911040045049</body></html>; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1461)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:325)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:147)

**Comment by zhmq0124v** [comment]
Thanks, your url works perfectly.
I also tried https://gitlab.com, it worked too.
But when access my own gitlab server, I still get the following exception. Is it because my gitlab server version too low or any other settings?(it works with python API)...

Exception in thread "main" org.gitlab.api.GitlabAPIException
	at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:361)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:149)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:119)
	at org.gitlab.api.GitlabAPI.getCurrentSession(GitlabAPI.java:1519)
	at UpdateIssues.main(UpdateIssues.java:21)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: <html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 1875165911041517243</body></html>; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1461)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
	at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:325)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:147)

**Comment by rockwotj** [comment]
I would think it would have to be either a setting on your GitLab server or possibly the version? I'm not sure, I've never ran into those issues. I feel like if the URL works in your browser then it should work in the Java code. 

What version of GitLab do you have?

**Comment by zhmq0124v** [comment]
I am using GITLAB 6.
Not sure why URL works but API does not work

**Comment by rockwotj** [comment]
The invalid SSL cert should not be the issue:

https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java#L367 

I think @timols will have to help you here, I don't have any insight for you. Sorry!

**Comment by zhmq0124v** [comment]
You can create a new user in https://git-lenovo.hybris.hec.ondemand.com/ and test the API.
@rockwotj @timols I had tried days, the site itself might have issues but I could not figure it out.

**Comment by rockwotj** [comment]
This is the data that I'm getting back from the HTTP request and this is the URL it's requesting: https://git-lenovo.hybris.hec.ondemand.com/api/v3/projects. But again, it works from the browser. 

Have you checked the GitLab logs?

```html
<html>
  <head>
    <title>Request Rejected</title>
  </head>
  <body>      
              The requested URL was rejected. 
              Please consult with your administrator.
              <br><br>
              Your support ID is: 1875165911045212184
  </body>
</html>
```

**Comment by zhmq0124v** [comment]
Sorry, I have no access to GitLab logs.
I am really confused, URL in browser works, Python API also works.
Did I missing something in my code or settings in GitLab?

**Comment by rockwotj** [comment]
I can't think of a settings issue. I'd have to look at the difference between the Python API and the Java client to see the difference

**Comment by zhmq0124v** [comment]
Now I even suspect this error message was sent from the proxy, not Gitlab server.
Could someone help check if GitlabAPI could access https://git-lenovo.hybris.hec.ondemand.com?

**Comment by zhmq0124v** [comment]
@rockwotj @timols the root cause has been found: remote Gitlab server requires valid browser(user-agent) information.
We need to check how Python overcomes this restriction.

**Comment by rockwotj** [comment]
You should be able to set the [User-Agent header](http://www.useragentstring.com/pages/useragentstring.php) [here](https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java#L316).

**Comment by zhmq0124v** [comment]
Thanks, issue has been resolved.
