### ISSUE TITLE
Not possible creating a label  - {"message":{"color":["must be a valid color code"]}}

### ISSUE THREAD

**Issue by soutaga** [timols/java-gitlab-api#163]
- Create label "type-bug" with color "#5cb85c"
  org.gitlab.api.GitlabAPIException: {"message":{"color":["must be a valid color code"]}}
  at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:369)
  at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:146)
  at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:116)
  at org.gitlab.api.GitlabAPI.createLabel(GitlabAPI.java:1512)
  ...
  Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: http://cie/gitlab/api/v3/projects/14/labels
  at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
  at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:327)
  at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:144)
  ... 5 more

**Comment by soutaga** [comment]
Hi,

I'm trying to use the API to create a new label and I'm geeting an error saying that the color code is not correct. 

I have created a different label manually using the same color and it was ok.

Any suggestion?

Thank you
