### ISSUE TITLE
(Un)Blocking a user results in GitlabAPIException

### ISSUE THREAD

**Issue by islandsvinur** [timols/java-gitlab-api#164]
Hi,

I have the following code:

```
GitlabAPI connect = GitlabAPI.connect("...", "...");
GitlabUser user = connect.getUserViaSudo("...");
connect.unblockUser(user.getId());
```

This consistently results in a `GitlabAPIException` caused by a `JsonMappingException`. The user is succesfully unblocked. The same exception also occurs with `blockUser`.

Self-hosted Gitlab version: 8.12.4

Stacktrace:

```
Exception in thread "main" org.gitlab.api.GitlabAPIException
    at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:369)
    at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:146)
    at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:116)
    at org.gitlab.api.GitlabAPI.unblockUser(GitlabAPI.java:274)
    at com.gxsoftware.GitLabRemote.main(GitLabRemote.java:18)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate value of type [simple type, class java.lang.Void] from Boolean value (true); no single-boolean/Boolean-arg constructor/factory method
 at [Source: true; line: 1, column: 1]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:843)
    at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromBoolean(StdValueInstantiator.java:352)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromBoolean(BeanDeserializerBase.java:1196)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:162)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2578)
    at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:330)
    at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:144)
    ... 8 more
```

**Comment by timols** [comment]
@islandsvinur I believe this issue has now been resolved with the release of 1.2.8
