### ISSUE TITLE
GitLab CE with Cloudflare

### ISSUE THREAD

**Issue by tweekowsky** [timols/java-gitlab-api#204]
Hi, 

I encountered a problem while trying to use your library. I'm using an instance of GitLab CE connected to Cloudflare and all traffic goes through them. Earlier i used GL api by simply requests like:

`curl --header "Authorization: Bearer token" "https://ci-buddy.com/api/v3/user"`

and it works fine, but when I try to use your lib with simple example like:

```
GitlabAPI gitlabAPI = GitlabAPI.connect("https://ci-buddy.com/api/v3/user", "token", TokenType.ACCESS_TOKEN, AuthMethod.HEADER)
GitlabUser user = gitlabAPI.getUser();
```

i get:

```
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.__newInstance(DelegatingConstructorAccessorImpl.java:45)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.gitlab.api.http.GitlabHTTPRequestor.handleAPIError(GitlabHTTPRequestor.java:436)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:170)
	at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:139)
	at org.gitlab.api.GitlabAPI.getUser(GitlabAPI.java:147)
```

Can you help me or just point what i'm doing wrong?

Regards,
Darek

**Comment by slskopytko** [comment]
I have the same error. any tip?

**Comment by timols** [comment]
@tweekowsky could you re-run your curl command with `-v` so we can see the headers curl is sending?

I've not seen that error before so I don't have any obvious suggestions.

**Comment by DoctorBlue** [comment]
I'm experiencing the same issue. Here's the output with verbose on in curl from our GitLab server behind CloudFlare.

```
curl --header "Authorization: Bearer <token>" "https://domain.dk/api/v3/user" -v                18:47:43 
*   Trying xxx.xxx.xxx.xxx...
* TCP_NODELAY set
* Connected to domain.dk (xxx.xxx.xxx.xxx) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* ALPN, server accepted to use h2
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate:
* 	subject: CN=sni12345.cloudflaressl.com,OU=PositiveSSL Multi-Domain,OU=Domain Control Validated
* 	start date: Mar 06 00:00:00 2017 GMT
* 	expire date: Sep 12 23:59:59 2017 GMT
* 	common name: sni12345.cloudflaressl.com
* 	issuer: CN=COMODO ECC Domain Validation Secure Server CA 2,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x564bdd7ced80)
> GET /api/v3/user HTTP/1.1
> Host: domain.dk
> User-Agent: curl/7.51.0
> Accept: */*
> Authorization: Bearer <token>
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Tue, 25 Apr 2017 16:47:51 GMT
< content-type: application/json
< content-length: 666
< set-cookie: __cfduid=dd947a309da73c9dca6f6a2aa64bdf6501493138871; expires=Wed, 25-Apr-18 16:47:51 GMT; path=/; domain=.domain.dk; HttpOnly
< cache-control: max-age=0, private, must-revalidate
< etag: W/"6cce3d83ef9f6c794eb3effcb2b52cce"
< vary: Origin
< x-request-id: 0bd427ef-a07e-4ff9-bad5-e1c265200037
< x-runtime: 0.028487
< server: cloudflare-nginx
< cf-ray: 3552c95aad3b3d67-CPH
< 
* Curl_http_done: called premature == 0
* Connection #0 to host backuptrain.dk left intact

```

**Comment by DoctorBlue** [comment]
Just an update: I only had issues with Buddy, which is where @tweekowsky is having the issues (I filed the issue there). I tried running the Java snippet you posted, but it seems to work fine for me on the exact GitLab installation that was causing issues.

**Comment by tweekowsky** [comment]
Here's verbose output:

```
*   Trying xxx.xxx.xxx.xxx...
* Connected to ci-buddy.com (xxx.xxx.xxx.xxx) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: sni103178.cloudflaressl.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: EC
* 	 certificate version: #3
* 	 subject: OU=Domain Control Validated,OU=PositiveSSL Multi-Domain,CN=sni103178.cloudflaressl.com
* 	 start date: Thu, 13 Apr 2017 00:00:00 GMT
* 	 expire date: Fri, 20 Oct 2017 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO ECC Domain Validation Secure Server CA 2
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> GET /api/v3/user HTTP/1.1
> Host: ci-buddy.com
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer d41da73db2a9fea39f40c24d35b3857353fb6db23cf083ea7f72226abe89a0a6
> 
< HTTP/1.1 200 OK
< Date: Wed, 26 Apr 2017 06:33:10 GMT
< Content-Type: application/json
< Content-Length: 679
< Connection: keep-alive
< Set-Cookie: __cfduid=d2096601229cebf967aaf5536cc107d571493188390; expires=Thu, 26-Apr-18 06:33:10 GMT; path=/; domain=.ci-buddy.com; HttpOnly
< Cache-Control: max-age=0, private, must-revalidate
< Etag: W/"dc842f47de961a5097c569b19073078c"
< Vary: Origin
< X-Request-Id: 702396c0-6c2c-4c5e-abdc-1432432580a9
< X-Runtime: 0.030084
< Strict-Transport-Security: max-age=31536000
< Server: cloudflare-nginx
< CF-RAY: 355782513ec77319-AMS
< 
* Connection #0 to host ci-buddy.com left intact
```

**Comment by tweekowsky** [comment]
Sorry for bother. Problem is in my webservice SSL configuration against cloudflare.
